FROM python:3-onbuild

COPY A2part1.py /usr/src/app
COPY A2part2.py /usr/src/app
COPY A2part3.py /usr/src/app
COPY A2part4.py /usr/src/app
COPY A2part5.py /usr/src/app


CMD ["python","A2part1.py"]

CMD ["python","A2part2.py"]

CMD ["python","A2part3.py"]

CMD ["python","A2part4.py"]

CMD ["python","A2part5.py"]

